version: '3.8'

services:
  generic-dynamodb-api:
    build: .
    ports:
      - "8001:8001"
    environment:
      - FLASK_ENV=development
      - PORT=8001
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - DYNAMODB_TABLE_NAME=${DYNAMODB_TABLE_NAME}
      - KEY_FIELD=${KEY_FIELD:-item_id}
      - TABLE_FIELDS=${TABLE_FIELDS}
      - DYNAMODB_ENDPOINT_URL=
      - API_KEY=${API_KEY}
    volumes:
      - .:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3 